name:                acme-circular-containers
version:             0.1.0.0
synopsis:            Spineless containers which are fast to read but inefficient to update
description:         Doubly-linked lists, doubly-linked trees, and naïvely-represented graphs, with each vertex literally pointing at its neighbours.
homepage:            https://github.com/gelisam/acme-circular-containers#readme
github:              gelisam/acme-circular-containers
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Acme
extra-source-files:
- README.md

dependencies:
  - base >= 4.9 && < 5
  - containers >= 0.5.8
  - graph-wrapper >= 0.2.6.0

library:
  source-dirs:      src
  ghc-options: -W -Wall

tests:
  doctests:
    source-dirs: tests
    main: doctests.hs
    dependencies:
      - doctest
      - doctest-discover
