name:                acme-circular-containers
version:             0.1.0.0
synopsis:            Spineless containers which are fast to read but inefficient to update
description:         Doubly-linked lists, doubly-linked trees, and naïvely-represented graphs, with each vertex literally pointing at its neighbours.
homepage:            https://github.com/gelisam/acme-circular-containers#readme
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Acme
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - graph-wrapper

library:
  source-dirs:      src
  ghc-options: -W -Wall

tests:
  doctests:
    source-dirs: tests
    main: doctests.hs
    dependencies:
      - doctest
      - doctest-discover
